configReload:
  configURL: https://raw.githubusercontent.com/asbachb/quadit-uranium/refs/heads/main/quadit-config.yml
  interval: 10000

targetConfigs:
- url: https://github.com/asbachb/quadit-uranium
  targetPath: "forgejo"
  branch: "main"
  schedule: "1/10 * * * * *"
